# Generated by Django 3.2.7 on 2024-11-23 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number', models.PositiveIntegerField(verbose_name='Номер квартиры')),
                ('pet_name', models.CharField(max_length=50, verbose_name='Кличка питомца')),
                ('pet_breed', models.CharField(max_length=100, verbose_name='Порода питомца')),
                ('walk_date', models.DateField(verbose_name='Дата прогулки')),
                ('walk_time', models.TimeField(choices=[(datetime.time(7, 0), '07:00'), (datetime.time(8, 0), '08:00'), (datetime.time(9, 0), '09:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 0), '22:00'), (datetime.time(23, 0), '23:00'), (datetime.time(7, 30), '07:30'), (datetime.time(8, 30), '08:30'), (datetime.time(9, 30), '09:30'), (datetime.time(10, 30), '10:30'), (datetime.time(11, 30), '11:30'), (datetime.time(12, 30), '12:30'), (datetime.time(13, 30), '13:30'), (datetime.time(14, 30), '14:30'), (datetime.time(15, 30), '15:30'), (datetime.time(16, 30), '16:30'), (datetime.time(17, 30), '17:30'), (datetime.time(18, 30), '18:30'), (datetime.time(19, 30), '19:30'), (datetime.time(20, 30), '20:30'), (datetime.time(21, 30), '21:30'), (datetime.time(22, 30), '22:30')], verbose_name='Время прогулки')),
                ('walker', models.CharField(choices=[('Петр', 'Петр'), ('Антон', 'Антон')], max_length=10, verbose_name='Кто выгуливает')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'unique_together': {('walk_date', 'walk_time', 'walker')},
            },
        ),
    ]
